/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_BAD_FIELD_ERROR: Unknown column '$1' in 'where clause'
    at Query.Sequence._packetToError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:198:25)
    at loginUser (/home/grafibook/api_automotora/userController.js:20:33)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at /home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:346:12)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:280:10)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:314:20)
    at Protocol._delegateError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Query.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:153:12)
    at Query.emit (events.js:314:20)
    at Query.Sequence.end (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:12)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column '$1' in 'where clause'",
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT * FROM users WHERE username = $1'
}
/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_BAD_FIELD_ERROR: Unknown column '$1' in 'where clause'
    at Query.Sequence._packetToError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:198:25)
    at loginUser (/home/grafibook/api_automotora/userController.js:20:33)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at /home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:346:12)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:280:10)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:314:20)
    at Protocol._delegateError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Query.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:153:12)
    at Query.emit (events.js:314:20)
    at Query.Sequence.end (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:12)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column '$1' in 'where clause'",
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT * FROM users WHERE username = $1'
}
/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_BAD_FIELD_ERROR: Unknown column '$1' in 'where clause'
    at Query.Sequence._packetToError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:198:25)
    at loginUser (/home/grafibook/api_automotora/userController.js:20:33)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at /home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:346:12)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:280:10)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:314:20)
    at Protocol._delegateError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Query.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:153:12)
    at Query.emit (events.js:314:20)
    at Query.Sequence.end (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:12)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column '$1' in 'where clause'",
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT * FROM users WHERE username = $1'
}
/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_BAD_FIELD_ERROR: Unknown column '$1' in 'where clause'
    at Query.Sequence._packetToError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:198:25)
    at loginUser (/home/grafibook/api_automotora/userController.js:20:33)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at /home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:346:12)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:280:10)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:314:20)
    at Protocol._delegateError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Query.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:153:12)
    at Query.emit (events.js:314:20)
    at Query.Sequence.end (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:12)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column '$1' in 'where clause'",
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT * FROM users WHERE username = $1'
}
/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_BAD_FIELD_ERROR: Unknown column '$1' in 'where clause'
    at Query.Sequence._packetToError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:198:25)
    at loginUser (/home/grafibook/api_automotora/userController.js:20:33)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at /home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:346:12)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:280:10)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:314:20)
    at Protocol._delegateError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Query.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:153:12)
    at Query.emit (events.js:314:20)
    at Query.Sequence.end (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:12)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column '$1' in 'where clause'",
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT * FROM users WHERE username = $1'
}
/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_BAD_FIELD_ERROR: Unknown column '$1' in 'where clause'
    at Query.Sequence._packetToError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:198:25)
    at loginUser (/home/grafibook/api_automotora/userController.js:20:33)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at /home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:346:12)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:280:10)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:314:20)
    at Protocol._delegateError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Query.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:153:12)
    at Query.emit (events.js:314:20)
    at Query.Sequence.end (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:12)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column '$1' in 'where clause'",
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT * FROM users WHERE username = $1'
}
/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_BAD_FIELD_ERROR: Unknown column '$1' in 'where clause'
    at Query.Sequence._packetToError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:198:25)
    at loginUser (/home/grafibook/api_automotora/userController.js:20:33)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at /home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:346:12)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:280:10)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:314:20)
    at Protocol._delegateError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Query.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:153:12)
    at Query.emit (events.js:314:20)
    at Query.Sequence.end (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:12)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column '$1' in 'where clause'",
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT * FROM users WHERE username = $1'
}
/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_BAD_FIELD_ERROR: Unknown column '$1' in 'where clause'
    at Query.Sequence._packetToError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:198:25)
    at loginUser (/home/grafibook/api_automotora/userController.js:20:33)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at /home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:346:12)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:280:10)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:314:20)
    at Protocol._delegateError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Query.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:153:12)
    at Query.emit (events.js:314:20)
    at Query.Sequence.end (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:12)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column '$1' in 'where clause'",
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT * FROM users WHERE username = $1'
}
/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_BAD_FIELD_ERROR: Unknown column '$1' in 'where clause'
    at Query.Sequence._packetToError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:198:25)
    at loginUser (/home/grafibook/api_automotora/userController.js:20:33)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at /home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:346:12)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:280:10)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:314:20)
    at Protocol._delegateError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Query.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:153:12)
    at Query.emit (events.js:314:20)
    at Query.Sequence.end (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:12)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column '$1' in 'where clause'",
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT * FROM users WHERE username = $1'
}
/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_BAD_FIELD_ERROR: Unknown column '$1' in 'where clause'
    at Query.Sequence._packetToError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:198:25)
    at loginUser (/home/grafibook/api_automotora/userController.js:20:33)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at /home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:346:12)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:280:10)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:314:20)
    at Protocol._delegateError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Query.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:153:12)
    at Query.emit (events.js:314:20)
    at Query.Sequence.end (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:12)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column '$1' in 'where clause'",
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT * FROM users WHERE username = $1'
}
/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_BAD_FIELD_ERROR: Unknown column '$1' in 'where clause'
    at Query.Sequence._packetToError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:198:25)
    at loginUser (/home/grafibook/api_automotora/userController.js:20:33)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at /home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:346:12)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:280:10)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:314:20)
    at Protocol._delegateError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Query.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:153:12)
    at Query.emit (events.js:314:20)
    at Query.Sequence.end (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:12)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column '$1' in 'where clause'",
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT * FROM users WHERE username = $1'
}
/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_BAD_FIELD_ERROR: Unknown column '$1' in 'where clause'
    at Query.Sequence._packetToError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:198:25)
    at loginUser (/home/grafibook/api_automotora/userController.js:22:33)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at /home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:346:12)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:280:10)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:314:20)
    at Protocol._delegateError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Query.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:153:12)
    at Query.emit (events.js:314:20)
    at Query.Sequence.end (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:12)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column '$1' in 'where clause'",
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT * FROM users WHERE username = $1'
}
/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_BAD_FIELD_ERROR: Unknown column '$1' in 'where clause'
    at Query.Sequence._packetToError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:198:25)
    at loginUser (/home/grafibook/api_automotora/userController.js:22:33)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/layer.js:95:5)
    at /home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:346:12)
    at next (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/express/lib/router/index.js:280:10)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:314:20)
    at Protocol._delegateError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Query.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:153:12)
    at Query.emit (events.js:314:20)
    at Query.Sequence.end (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:12)
    at Query.ErrorPacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Parser.js:43:10) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column '$1' in 'where clause'",
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT * FROM users WHERE username = $1'
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:112:13)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:94:28)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:314:20)
    at Protocol._delegateError (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.end (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/protocol/Protocol.js:116:8)
    at Socket.<anonymous> (/home/grafibook/nodevenv/api_automotora/12/lib/node_modules/mysql/lib/Connection.js:94:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'mysql'
Require stack:
- /home/grafibook/api_automotora/db.js
- /home/grafibook/api_automotora/carController.js
- /home/grafibook/api_automotora/app.js
- /usr/local/lsws/fcgi-bin/lsnode.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/grafibook/api_automotora/db.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/grafibook/api_automotora/db.js',
    '/home/grafibook/api_automotora/carController.js',
    '/home/grafibook/api_automotora/app.js',
    '/usr/local/lsws/fcgi-bin/lsnode.js'
  ]
}
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'mysql'
Require stack:
- /home/grafibook/api_automotora/db.js
- /home/grafibook/api_automotora/carController.js
- /home/grafibook/api_automotora/app.js
- /usr/local/lsws/fcgi-bin/lsnode.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/grafibook/api_automotora/db.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/grafibook/api_automotora/db.js',
    '/home/grafibook/api_automotora/carController.js',
    '/home/grafibook/api_automotora/app.js',
    '/usr/local/lsws/fcgi-bin/lsnode.js'
  ]
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Object.<anonymous> (/home/grafibook/api_automotora/app.js:315:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
